"use client"

import React from 'react'
import { Input } from '@/components/ui/input'
import { useFormatBuilder } from '../format-builder-context'

export function BackgroundZoneStyles({ showContentControls = true }: { showContentControls?: boolean }) {
  const { selectedZone, updateZone, updateZoneStyle, registerBlob, revokeBlob } = useFormatBuilder()
  if (!selectedZone || selectedZone.type !== 'background') return null

  const s = (selectedZone as any).style || {}
  const update = (u: Record<string, any>) => updateZoneStyle(selectedZone.id, u)

  return (
    <div className="space-y-2">
      <label className="text-[10px] text-gray-500 uppercase block border-b border-gray-800 pb-1">Background Style</label>
      <div>
        <label className="text-[10px] text-gray-500 block">Type</label>
        <select value={s.type || 'gradient'} onChange={e => update({ type: e.target.value })} className="w-full h-6 text-[10px] bg-gray-900 border border-gray-700 rounded text-white">
          <option value="solid">Solid Color</option>
          <option value="gradient">Gradient</option>
          <option value="image">Image</option>
          <option value="pattern">Pattern</option>
        </select>
      </div>

      {s.type === 'solid' && (
        <div>
          <label className="text-[10px] text-gray-500 block">Color</label>
          <div className="flex items-center gap-2">
            <input type="color" value={s.color || '#0f172a'} onChange={e => update({ color: e.target.value })} className="w-7 h-7 rounded border border-gray-700 cursor-pointer bg-transparent" />
            <span className="text-[9px] text-gray-600 font-mono">{s.color || '#0f172a'}</span>
          </div>
        </div>
      )}

      {s.type === 'gradient' && (
        <>
          <div className="grid grid-cols-2 gap-2">
            <div>
              <label className="text-[10px] text-gray-500 block">Color 1</label>
              <input type="color" value={s.gradientColor1 || '#0f172a'} onChange={e => update({ gradientColor1: e.target.value })} className="w-full h-6 rounded border border-gray-700 cursor-pointer bg-transparent" />
            </div>
            <div>
              <label className="text-[10px] text-gray-500 block">Color 2</label>
              <input type="color" value={s.gradientColor2 || '#1e293b'} onChange={e => update({ gradientColor2: e.target.value })} className="w-full h-6 rounded border border-gray-700 cursor-pointer bg-transparent" />
            </div>
          </div>
          <div>
            <label className="text-[10px] text-gray-500 block">Direction</label>
            <select value={s.gradientDirection || '135deg'} onChange={e => update({ gradientDirection: e.target.value })} className="w-full h-6 text-[10px] bg-gray-900 border border-gray-700 rounded text-white">
              <option value="0deg">Top → Bottom</option>
              <option value="90deg">Left → Right</option>
              <option value="135deg">Diagonal ↘</option>
              <option value="180deg">Bottom → Top</option>
              <option value="270deg">Right → Left</option>
              <option value="45deg">Diagonal ↗</option>
            </select>
          </div>
        </>
      )}

      {s.type === 'image' && (
        <>
          {showContentControls ? (
            <>
              <div>
                <label className="text-[10px] text-gray-500 block">Image URL</label>
                <Input value={s.imageUrl || ''} onChange={e => update({ imageUrl: e.target.value })} className="h-6 text-[10px] bg-gray-900 border-gray-700 text-white" placeholder="https://…" />
              </div>
              <div>
                <label className="text-[10px] text-gray-500 block mb-1">Upload Background Image</label>
                <label className="flex items-center justify-center gap-1 px-3 py-2 rounded-md border border-dashed border-gray-600 text-[10px] text-gray-400 hover:border-gray-500 hover:text-gray-300 cursor-pointer transition-colors">
                  <span>Choose file or drop here</span>
                  <input
                    type="file"
                    accept="image/*"
                    className="hidden"
                    onChange={e => {
                      const file = e.target.files?.[0]
                      if (!file) return
                      revokeBlob(s.imageUrl || '') // revoke old blob if replacing
                      const blobUrl = registerBlob(file)
                      update({ imageUrl: blobUrl })
                    }}
                  />
                </label>
              </div>
            </>
          ) : (
            <div className="p-2.5 rounded border border-orange-500/10 bg-orange-500/5 text-center my-1">
              <p className="text-[10px] text-orange-400 font-semibold">
                📷 Background image will be generated by AI
              </p>
            </div>
          )}
          <div>
            <label className="text-[10px] text-gray-500 block">Fit</label>
            <select value={s.imageFit || 'cover'} onChange={e => update({ imageFit: e.target.value })} className="w-full h-6 text-[10px] bg-gray-900 border border-gray-700 rounded text-white">
              <option value="cover">Cover</option>
              <option value="contain">Contain</option>
              <option value="fill">Fill</option>
            </select>
          </div>
          <div className="space-y-1.5 pt-1">
            <div className="flex items-center justify-between">
              <label className="text-[10px] text-gray-500 font-medium">Opacity</label>
              <span className="text-[10px] text-gray-300 font-mono font-semibold">{s.imageOpacity ?? 100}%</span>
            </div>
            <input
              type="range"
              min="0"
              max="100"
              value={s.imageOpacity ?? 100}
              onChange={e => update({ imageOpacity: parseInt(e.target.value, 10) })}
              className="w-full h-1.5 bg-gray-800 rounded-lg appearance-none cursor-pointer accent-indigo-500"
            />
          </div>

          <div className="space-y-1.5 pt-1">
            <div className="flex items-center justify-between">
              <label className="text-[10px] text-gray-500 font-medium">Blur</label>
              <span className="text-[10px] text-gray-300 font-mono font-semibold">{s.imageBlur ?? 0}px</span>
            </div>
            <input
              type="range"
              min="0"
              max="20"
              step="1"
              value={s.imageBlur ?? 0}
              onChange={e => update({ imageBlur: parseInt(e.target.value, 10) })}
              className="w-full h-1.5 bg-gray-800 rounded-lg appearance-none cursor-pointer accent-indigo-500"
            />
          </div>
        </>
      )}

      {s.type === 'pattern' && (
        <div className="grid grid-cols-2 gap-2">
          <div>
            <label className="text-[10px] text-gray-500 block">Pattern</label>
            <select value={s.patternType || 'dots'} onChange={e => update({ patternType: e.target.value })} className="w-full h-6 text-[10px] bg-gray-900 border border-gray-700 rounded text-white">
              <option value="dots">Dots</option>
              <option value="lines">Lines</option>
              <option value="grid">Grid</option>
              <option value="diagonal">Diagonal</option>
            </select>
          </div>
          <div>
            <label className="text-[10px] text-gray-500 block">Opacity</label>
            <Input type="number" step="0.1" min="0" max="1" value={s.patternOpacity ?? 0.3} onChange={e => update({ patternOpacity: parseFloat(e.target.value) })} className="h-6 text-[10px] bg-gray-900 border-gray-700 text-white" />
          </div>
        </div>
      )}
    </div>
  )
}

function parseOverlay(overlayStr?: string): { color: string; opacity: number } {
  if (!overlayStr) return { color: '#000000', opacity: 50 }
  
  const rgbaMatch = overlayStr.match(/rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)(?:\s*,\s*([\d.]+))?\s*\)/i)
  if (rgbaMatch) {
    const r = parseInt(rgbaMatch[1], 10)
    const g = parseInt(rgbaMatch[2], 10)
    const b = parseInt(rgbaMatch[3], 10)
    const a = rgbaMatch[4] !== undefined ? parseFloat(rgbaMatch[4]) : 1
    const hex = `#${((1 << 24) + (r << 16) + (g << 8) + b).toString(16).slice(1)}`
    return { color: hex, opacity: Math.round(a * 100) }
  }

  if (overlayStr.startsWith('#')) {
    if (overlayStr.length === 9) {
      const hexColor = overlayStr.slice(0, 7)
      const alphaHex = overlayStr.slice(7, 9)
      const a = parseInt(alphaHex, 16) / 255
      return { color: hexColor, opacity: Math.round(a * 100) }
    }
    return { color: overlayStr, opacity: 100 }
  }

  return { color: '#000000', opacity: 50 }
}

function formatOverlay(hexColor: string, opacityPercent: number): string {
  if (opacityPercent === 0) return ''
  const hex = hexColor.replace('#', '')
  const r = parseInt(hex.substring(0, 2) || '0', 16)
  const g = parseInt(hex.substring(2, 4) || '0', 16)
  const b = parseInt(hex.substring(4, 6) || '0', 16)
  const alpha = (opacityPercent / 100).toFixed(2)
  return `rgba(${r}, ${g}, ${b}, ${alpha})`
}

function OverlayControl({ overlayValue, onChange }: { overlayValue?: string; onChange: (val: string) => void }) {
  const { color, opacity } = parseOverlay(overlayValue)
  const [hexColor, setHexColor] = React.useState(color)

  React.useEffect(() => {
    setHexColor(color)
  }, [color])

  const handleOpacityChange = (newOpacity: number) => {
    onChange(formatOverlay(hexColor, newOpacity))
  }

  const handleColorChange = (newColor: string) => {
    setHexColor(newColor)
    onChange(formatOverlay(newColor, opacity))
  }

  return (
    <div className="space-y-1.5 pt-1">
      <div className="flex items-center justify-between">
        <label className="text-[10px] text-gray-400 font-medium">Overlay Opacity</label>
        <span className="text-[10px] text-gray-300 font-mono font-semibold">{opacity}%</span>
      </div>
      <div className="flex items-center gap-2">
        <input
          type="color"
          value={hexColor}
          onChange={e => handleColorChange(e.target.value)}
          className="w-6 h-6 rounded border border-gray-700 cursor-pointer bg-transparent flex-shrink-0"
          title="Overlay Color"
        />
        <input
          type="range"
          min="0"
          max="100"
          value={opacity}
          onChange={e => handleOpacityChange(parseInt(e.target.value, 10))}
          className="w-full h-1.5 bg-gray-800 rounded-lg appearance-none cursor-pointer accent-indigo-500"
        />
      </div>
    </div>
  )
}
