"use client"
 
import React from 'react'
import { Input } from '@/components/ui/input'
import { useFormatBuilder } from '../format-builder-context'
import type { ImageZone, ImageZoneStyle } from '@/lib/format-types'
import { Link, UploadCloud, Trash2, ChevronDown, Sliders } from 'lucide-react'

export function ImageZoneStyles({ showContentControls = true }: { showContentControls?: boolean }) {
  const { selectedZone, updateZone, updateZoneStyle, registerBlob, revokeBlob } = useFormatBuilder()
  if (!selectedZone || selectedZone.type !== 'image') return null
 
  const zone = selectedZone as ImageZone
  const s = zone.style || {}
  const imageUrl = zone.imageUrl || ''
  const isLocalImage = imageUrl.startsWith('data:') || imageUrl.startsWith('blob:')
 
  const updateStyle = (u: Partial<ImageZoneStyle>) => updateZoneStyle(zone.id, u)

  const handleRemoveImage = () => {
    revokeBlob(imageUrl)
    updateZone(zone.id, { imageUrl: '' } as any)
  }
 
  return (
    <div className="space-y-4">
      <label className="text-[10px] text-gray-400 uppercase font-bold tracking-wider block border-b border-gray-800 pb-1.5">
        Image Properties
      </label>
 
      {/* ── Image URL Input & Upload ── */}
      {showContentControls ? (
        <div className="space-y-3 bg-[#0e0e1a]/20 p-2.5 rounded-lg border border-gray-800">
          <div>
            <label className="text-[10px] text-gray-500 block mb-1">Image URL</label>
            {isLocalImage ? (
              <div className="flex items-center justify-between gap-2 px-2.5 py-1.5 rounded-md border border-gray-800 bg-gray-950 text-xs">
                <div className="flex items-center gap-2 text-gray-400 truncate">
                  <UploadCloud className="w-3.5 h-3.5 text-orange-400 shrink-0" />
                  <span className="text-[10px] font-semibold text-gray-300 truncate">Local Image Uploaded</span>
                </div>
                <button
                  onClick={handleRemoveImage}
                  className="p-1 hover:bg-gray-800 hover:text-red-400 text-gray-500 rounded transition-colors shrink-0"
                  title="Remove Image"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              </div>
            ) : (
              <div className="relative flex items-center">
                <Link className="absolute left-2.5 w-3.5 h-3.5 text-gray-600" />
                <Input
                  value={imageUrl}
                  onChange={e => updateZone(zone.id, { imageUrl: e.target.value } as any)}
                  placeholder="https://... or paste image URL"
                  className="pl-8 pr-8 h-8 text-[11px] bg-gray-950 border-gray-800 text-white placeholder:text-gray-650 focus:outline-none focus:border-orange-500/40 rounded-md transition-all"
                />
                {imageUrl && (
                  <button
                    onClick={handleRemoveImage}
                    className="absolute right-2 text-gray-500 hover:text-gray-300 p-0.5"
                  >
                    <Trash2 className="w-3 h-3" />
                  </button>
                )}
              </div>
            )}
          </div>
 
          <div>
            <label className="text-[10px] text-gray-500 block mb-1">Upload Image</label>
            <label className="flex flex-col items-center justify-center gap-1.5 px-3 py-3 rounded-lg border border-dashed border-gray-800 bg-gray-950/20 text-[10px] text-gray-400 hover:border-orange-500/40 hover:text-gray-300 hover:bg-orange-500/5 cursor-pointer transition-all group">
              <UploadCloud className="w-5 h-5 text-gray-500 group-hover:text-orange-400 transition-colors" />
              <span className="font-semibold">Choose image file or drag here</span>
              <input
                type="file"
                accept="image/*"
                className="hidden"
                onChange={e => {
                  const file = e.target.files?.[0]
                  if (!file) return
                  revokeBlob(imageUrl) // revoke old blob if replacing
                  const blobUrl = registerBlob(file)
                  updateZone(zone.id, { imageUrl: blobUrl } as any)
                }}
              />
            </label>
          </div>
        </div>
      ) : (
        <div className="p-2.5 rounded border border-orange-500/10 bg-orange-500/5 text-center">
          <p className="text-[10px] text-orange-400 font-semibold">
            📷 Image content will be generated by AI
          </p>
        </div>
      )}
 
      {/* ── Fit & Radius ── */}
      <div className="grid grid-cols-2 gap-3 pt-1">
        <div>
          <label className="text-[10px] text-gray-500 block mb-1">Fit Mode</label>
          <div className="relative">
            <select
              value={s.imageFit || 'cover'}
              onChange={e => updateStyle({ imageFit: e.target.value as any })}
              className="w-full h-8 text-[11px] bg-gray-950 border border-gray-800 rounded-md text-white px-2.5 focus:outline-none focus:border-orange-500/40 cursor-pointer appearance-none"
            >
              <option value="cover">Cover (Crop)</option>
              <option value="contain">Contain (Letterbox)</option>
              <option value="fill">Fill (Stretch)</option>
            </select>
            <ChevronDown className="absolute right-2.5 top-2.5 w-3.5 h-3.5 text-gray-500 pointer-events-none" />
          </div>
        </div>
        <div>
          <label className="text-[10px] text-gray-500 block mb-1">Corner Radius</label>
          <div className="relative flex items-center">
            <Sliders className="absolute left-2.5 w-3.5 h-3.5 text-gray-600" />
            <Input
              type="number"
              min="0"
              value={s.borderRadius ?? 8}
              onChange={e => updateStyle({ borderRadius: parseInt(e.target.value) || 0 })}
              className="pl-8 h-8 text-[11px] bg-gray-950 border-gray-800 text-white focus:outline-none focus:border-orange-500/40 rounded-md [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
            />
          </div>
        </div>
      </div>
 
      {/* ── Background Color (fallback/underlay) ── */}
      <div className="pt-1">
        <label className="text-[10px] text-gray-500 block mb-1">Fallback Color</label>
        <div className="flex items-center gap-2 p-1.5 bg-[#0e0e1a]/30 border border-gray-800 rounded-md max-w-[150px]">
          <div className="relative w-6 h-6 rounded border border-gray-800 overflow-hidden cursor-pointer shrink-0 bg-[#1e293b]">
            <input
              type="color"
              value={s.backgroundColor || '#1e293b'}
              onChange={e => updateStyle({ backgroundColor: e.target.value })}
              className="absolute inset-0 w-[200%] h-[200%] -translate-x-[25%] -translate-y-[25%] cursor-pointer bg-transparent border-0 p-0"
            />
          </div>
          <span className="text-[10px] text-gray-400 font-mono uppercase font-semibold">
            {s.backgroundColor || '#1E293B'}
          </span>
        </div>
      </div>
 
      {/* ── Mini Image Preview ── */}
      {imageUrl && (
        <div className="mt-2 rounded-lg overflow-hidden border border-gray-800 bg-gray-950/45 p-1.5">
          <div className="relative aspect-video w-full rounded-md overflow-hidden border border-gray-900 bg-[#12121e]">
            <img
              src={imageUrl}
              alt="Preview"
              className="w-full h-full"
              style={{
                objectFit: s.imageFit || 'cover',
                backgroundColor: s.backgroundColor || '#1e293b',
              }}
            />
            <div className="absolute top-1.5 left-1.5 px-2 py-0.5 rounded-full bg-black/60 backdrop-blur-sm text-[8px] font-bold uppercase tracking-wider text-gray-300 select-none">
              {s.imageFit || 'cover'}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
