export const dragState = {
    isDragging: false,
    dragType: '' as 'image' | 'text' | 'shape' | '',
    dragId: '',
    dragOffsetX: 0,
    dragOffsetY: 0,
    isResizing: false,
    isRotating: false,
    resizeHandle: '' as 'nw' | 'ne' | 'sw' | 'se' | 'n' | 'e' | 's' | 'w' | 'rotation' | '',
    startX: 0,
    startY: 0,
    startWidth: 0,
    startHeight: 0,
    startRotation: 0,
    centerX: 0,
    centerY: 0,
    isDrawingFreehand: false,
    drawingPoints: [] as { x: number, y: number }[],
    isHovering: false,
}
